parameters:
  myparameter:
    myvalue: 'This is a sample string config value'

  datalake:
    basePath: '/%kernel.environment%/'

  datalakebundle:
    tables:
      bronze_covid.tbl_template_1:
        schemaPath: '__myproject__.bronze_covid.tbl_template_1.schema'
        source_csv_path: 'dbfs:/databricks-datasets/COVID/covid-19-data/mask-use/mask-use-by-county.csv'
        # targetPath is automatically resolved, if non-standard location required, define var targetPath