imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '1021-090514-dolly408'
    orgId: '8394585307568385' # Azure Databricks only
    #workspaceBaseDir: '/master' # change to '/{currentBranch}' to use current branch name as dir name
    workspaceBaseDir: '/bricksflow-template/{currentBranch}' #to use current branch name as dir name