parameters:
  myparameter:
    myvalue: 'This is a sample string config value'

  datalake:
    basePath: '/%kernel.environment%/'

  datalakebundle:
    tables:
      # Bronze Covid tables
      # [databae_name].[table_name]
      bronze_covid.tbl_template_1_mask_usage:
        schemaPath: '__myproject__.bronze.covid.tbl_template_1_mask_usage.schema'
        source_csv_path: 'dbfs:/databricks-datasets/COVID/covid-19-data/mask-use/mask-use-by-county.csv'
        # targetPath: 'dbfs:/foo/bar.delta # is automatically resolved, if non-standard location required, define var targetPath

      bronze_covid.tbl_template_2_confirmed_cases:
        schemaPath: '__myproject__.bronze.covid.tbl_template_2_confirmed_cases.schema'
        source_csv_path: 'dbfs:/databricks-datasets/COVID/USAFacts/covid_confirmed_usafacts.csv'

      # Silver Covid tables
      silver_covid.tbl_template_3_mask_usage:
        schemaPath: '__myproject__.silver.covid.tbl_template_3_mask_usage.schema'

      # Gold tables
      gold_reporting.tbl_template_4_mask_usage_per_county:
        schemaPath: '__myproject__.gold.reporting.tbl_template_4_mask_usage_per_county.schema'