[tool.poetry]
name = "t__myproject__t"
version = "0.1"
description = "Bricksflow project skelefon"
readme = "README.md"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml", "*.json"]

packages = [
    { include = "__myproject__", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
pyfony-core = ">=0.7.0a3" # TODO: je tohle nakonec potřeba?
databricks-bundle = ">=0.6.0a10"
datalake-bundle = ">=0.5.0a5"

[tool.poetry.dev-dependencies]
databricks-connect = ">=7.3.5"
dbx-deploy = ">=0.13.0a4"
pylint = "2.4.*"
deepdiff = "^4.3.2"

[tool.poetry.plugins."bricksflow.app"]
container-init = "__myproject__.ContainerInit:initContainer"
#container-init = "bricksflowcore.container.containerInit:initContainer"
#root-module-name = "__myproject__"

[pyfony.bootstrap]
container-init = "__myproject__.ContainerInit:initContainer"
#container-init = "bricksflowcore.container.containerInit:initContainer"
#root-module-name = "__myproject__"
